"""update db

Revision ID: 2d722d168306
Revises: 5ed71e62f06d
Create Date: 2024-07-24 14:41:13.645024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d722d168306'
down_revision = '5ed71e62f06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('_password',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
